In [17]:
# import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [18]:
# import dataset
df = pd.read_csv('cleaned_data.csv')

In [19]:
# divide into x and y
x = df.drop(columns = ['Outcome'])
y = df[['Outcome']]

In [20]:
x

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,6,148.0,72.0,35.0,125.0,33.6,0.627,50
1,1,85.0,66.0,29.0,125.0,26.6,0.351,31
2,8,183.0,64.0,29.0,125.0,23.3,0.672,32
3,1,89.0,66.0,23.0,94.0,28.1,0.167,21
4,0,137.0,40.0,35.0,168.0,43.1,2.288,33
...,...,...,...,...,...,...,...,...
763,10,101.0,76.0,48.0,180.0,32.9,0.171,63
764,2,122.0,70.0,27.0,125.0,36.8,0.340,27
765,5,121.0,72.0,23.0,112.0,26.2,0.245,30
766,1,126.0,60.0,29.0,125.0,30.1,0.349,47
767,1,93.0,70.0,31.0,125.0,30.4,0.315,23

In [21]:
y

     Outcome
0          1
1          0
2          1
3          0
4          1
..       ...
763        0
764        0
765        0
766        1
767        0

[768 rows x 1 columns]

In [22]:
# feature scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x = pd.DataFrame(data = sc.fit_transform(x),columns = x.columns)

In [23]:
# divide into train and test
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.1,random_state = 0,stratify = y)

In [24]:
print(y_train['Outcome'].value_counts())
print(y_test['Outcome'].value_counts())

Outcome
0    450
1    241
Name: count, dtype: int64
Outcome
0    50
1    27
Name: count, dtype: int64

In [25]:
# create balanced data in training using SMOTE
from imblearn.over_sampling import SMOTE
smote = SMOTE(random_state = 42)
x_resampled, y_resampled = smote.fit_resample(x_train,y_train)

In [28]:
print(x_train.isnull().sum())

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
dtype: int64

In [29]:
y_resampled['Outcome'].value_counts()

Outcome
0    450
1    450
Name: count, dtype: int64

In [32]:
# build model and train
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(x_resampled,y_resampled)

# evaluate model
from sklearn.metrics import confusion_matrix,accuracy_score
y_pred = model.predict(x_test)
y_pred = pd.DataFrame(data = y_pred,columns = ['Prediction'])
result = pd.concat([y_test.reset_index(drop = True), y_pred], axis = 1)
cm = confusion_matrix(result['Outcome'], result['Prediction'])
score = accuracy_score(result['Outcome'], result['Prediction'])
print(cm)
print(score)

[[41  9]
 [ 6 21]]
0.8051948051948052

In [34]:
# build model and train -DecisionTreeClassifier
from sklearn.tree import DecisionTreeClassifier
model_dt = DecisionTreeClassifier(criterion = 'gini')
model_dt.fit(x_resampled, y_resampled)

#evaluate model
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = model_dt.predict(x_test)
y_pred = pd.DataFrame(data = y_pred, columns = ['Prediction'])
result = pd.concat([y_test.reset_index(drop = True), y_pred], axis = 1)
cm = confusion_matrix(result['Outcome'], result['Prediction'])
score = accuracy_score(result['Outcome'], result['Prediction'])
print(cm)
print(score)

[[45  5]
 [11 16]]
0.7922077922077922

In [35]:
#build model and train - RandomForestClassifier
from sklearn.ensemble import RandomForestClassifier
model_rf = RandomForestClassifier(n_estimators = 101)
model_rf.fit(x_resampled, y_resampled)

#evaluate model
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = model_rf.predict(x_test)
y_pred = pd.DataFrame(data = y_pred, columns = ['Prediction'])
result = pd.concat([y_test.reset_index(drop = True), y_pred], axis = 1)
cm = confusion_matrix(result['Outcome'], result['Prediction'])
score = accuracy_score(result['Outcome'], result['Prediction'])
print(cm)
print(score)

[[43  7]
 [ 9 18]]
0.7922077922077922

In [37]:
#build and train model - KNN
from sklearn.neighbors import KNeighborsClassifier
model_knn = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
model_knn.fit(x_resampled, y_resampled)

#evaluate model
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = model_knn.predict(x_test)
y_pred = pd.DataFrame(data = y_pred, columns = ['Prediction'])
result = pd.concat([y_test.reset_index(drop = True), y_pred], axis = 1)
cm = confusion_matrix(result['Outcome'], result['Prediction'])
score = accuracy_score(result['Outcome'], result['Prediction'])
print(cm)
print(score)

[[38 12]
 [ 7 20]]
0.7532467532467533

In [38]:
#build model and train - GaussianNB
from sklearn.naive_bayes import GaussianNB
model_nb = GaussianNB()
model_nb.fit(x_resampled, y_resampled)

#evaluate model
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = model_nb.predict(x_test)
y_pred = pd.DataFrame(data = y_pred, columns = ['Prediction'])
result = pd.concat([y_test.reset_index(drop = True), y_pred], axis = 1)
cm = confusion_matrix(result['Outcome'], result['Prediction'])
score = accuracy_score(result['Outcome'], result['Prediction'])
print(cm)
print(score)

[[40 10]
 [ 9 18]]
0.7532467532467533

In [40]:
#build model and train - SVC
from sklearn.svm import SVC
model_svc = SVC(kernel = 'rbf')
model_svc.fit(x_resampled, y_resampled)

#evaluate model
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = model_svc.predict(x_test)
y_pred = pd.DataFrame(data = y_pred, columns = ['Prediction'])
result = pd.concat([y_test.reset_index(drop = True), y_pred], axis = 1)
cm = confusion_matrix(result['Outcome'], result['Prediction'])
score = accuracy_score(result['Outcome'], result['Prediction'])
print(cm)
print(score)

[[43  7]
 [ 6 21]]
0.8311688311688312

In [41]:
#accuracy score of SVC algo is large so choose to export this model
import pickle
pickle.dump(model_svc, open('model.pkl', 'wb'))
pickle.dump(sc, open('sc.pkl', 'wb'))

In [45]:
columns = ['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Age']
myinput = [[1, 150, 8, 35, 13, 30, 0.65, 21]]
myinput = pd.DataFrame(data  = myinput, columns = columns)
myinput = pd.DataFrame(data  = sc.transform(myinput), columns = columns)
result = model_rf.predict(myinput)
if result[0] == 0:
    print("No, patient is not diabetic")
else:
    print("Yes, patient is diabetic")

No, patient is not diabetic